# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Church_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directingName', models.CharField(max_length=32)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=65)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('dni', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
                ('address', models.CharField(max_length=65)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('occupation', models.CharField(blank=True, max_length=65)),
                ('level', models.CharField(blank=True, max_length=65)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Cell')),
                ('church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongsTo', to='bd.Church')),
                ('directingChurch', models.ManyToManyField(through='bd.Church_Member', to='bd.Church')),
            ],
        ),
        migrations.CreateModel(
            name='member_praises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruments', models.ManyToManyField(to='bd.Instrument')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry_Directing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('directing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Ministry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=124)),
                ('type', models.CharField(max_length=32)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Institution')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lyric', models.TextField()),
                ('mp3', models.BinaryField(blank=True, null=True)),
                ('video', models.BinaryField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='praise',
            name='Songs',
            field=models.ManyToManyField(blank=True, to='bd.Song'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='directings',
            field=models.ManyToManyField(through='bd.Ministry_Directing', to='bd.Member'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(related_name='members', to='bd.Member'),
        ),
        migrations.AddField(
            model_name='member_praises',
            name='praise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Praise'),
        ),
        migrations.AddField(
            model_name='member',
            name='praises',
            field=models.ManyToManyField(through='bd.member_praises', to='bd.Praise'),
        ),
        migrations.AddField(
            model_name='church_member',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Member'),
        ),
        migrations.AddField(
            model_name='church',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Designation'),
        ),
        migrations.AddField(
            model_name='cell',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Church'),
        ),
        migrations.AddField(
            model_name='cell',
            name='directing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directing', to='bd.Member'),
        ),
        migrations.AddField(
            model_name='cell',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='bd.Member'),
        ),
    ]
