# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name': 'Celula'},
        ),
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name': 'Iglesia'},
        ),
        migrations.AlterModelOptions(
            name='church_member',
            options={'verbose_name': 'Cargo en Iglesia', 'verbose_name_plural': 'Cargos en Iglesias'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name': 'Denominacion', 'verbose_name_plural': 'Denominaciones'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institucion', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'Instrumento'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Miembro'},
        ),
        migrations.AlterModelOptions(
            name='member_praises',
            options={'verbose_name': 'Participante'},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name': 'Ministerio'},
        ),
        migrations.AlterModelOptions(
            name='ministry_directing',
            options={'verbose_name': 'Dirigente'},
        ),
        migrations.AlterModelOptions(
            name='moneytransaction',
            options={'verbose_name': 'Transaccion Monetaria', 'verbose_name_plural': 'Transacciones Monetarias'},
        ),
        migrations.AlterModelOptions(
            name='praise',
            options={'verbose_name': 'Alabanza'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='address',
            field=models.CharField(max_length=124, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Church', verbose_name='Iglesia'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='directing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directing', to='bd.Member', verbose_name='dirigente'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='bd.Member', verbose_name='anfitrion'),
        ),
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.CharField(max_length=65, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='church',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Designation', verbose_name='denominacion'),
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(max_length=25, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='church',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='church_member',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Church', verbose_name='iglesia'),
        ),
        migrations.AlterField(
            model_name='church_member',
            name='directingName',
            field=models.CharField(max_length=32, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=25, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.CharField(max_length=65, verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=25, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=25, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=65, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Cell', verbose_name='celula'),
        ),
        migrations.AlterField(
            model_name='member',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongsTo', to='bd.Church', verbose_name='iglesia'),
        ),
        migrations.AlterField(
            model_name='member',
            name='directingChurch',
            field=models.ManyToManyField(through='bd.Church_Member', to='bd.Church', verbose_name='cargos en Iglesias'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dni',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='carnet de identidad'),
        ),
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(blank=True, max_length=65, verbose_name='nivel educacional'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=65, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=65, verbose_name='ocupacion'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='praises',
            field=models.ManyToManyField(through='bd.member_praises', to='bd.Praise', verbose_name='alabanzas en que participa'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Church', verbose_name='iglesia'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='directings',
            field=models.ManyToManyField(through='bd.Ministry_Directing', to='bd.Member', verbose_name='dirigente'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(related_name='members', to='bd.Member', verbose_name='miembros'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(max_length=32, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='ministry_directing',
            name='name',
            field=models.CharField(max_length=32, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='date',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='description',
            field=models.CharField(max_length=124, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Institution', verbose_name='institucion que dona'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Member', verbose_name='miembro que dona'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='type',
            field=models.CharField(max_length=32, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='Songs',
            field=models.ManyToManyField(blank=True, to='bd.Song', verbose_name='Canciones'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='date',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(blank=True, max_length=25, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyric',
            field=models.TextField(verbose_name='letra'),
        ),
        migrations.AlterField(
            model_name='song',
            name='mp3',
            field=models.BinaryField(blank=True, null=True, verbose_name='mp3'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=25, verbose_name='nombre'),
        ),
    ]
