# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 01:56
from __future__ import unicode_literals

import bd.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_auto_20160417_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='phone',
            field=models.CharField(max_length=25, validators=[bd.models.PhoneValidator], verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.CharField(max_length=65, validators=[django.core.validators.EmailValidator('El correo no es valido')], verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=25, validators=[bd.models.PhoneValidator], verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dni',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11, 'El carnet debe tener 11 digitos'), django.core.validators.MaxLengthValidator(11, 'El carnet debe tener 11 digitos'), bd.models.DNIValidator], verbose_name='carnet de identidad'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[bd.models.PhoneValidator], verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Las transacciones tiene que tener monto mayor que 0')], verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='type',
            field=models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=32, verbose_name='tipo'),
        ),
    ]
