# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_auto_20160421_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cell',
        ),
        migrations.AddField(
            model_name='cell',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='bd.Member', verbose_name='miembro'),
        ),
    ]
