# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_auto_20160421_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('femmale', 'Femenino'), ('male', 'Masculino')], default='', max_length=32, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprovado'), ('denied', 'Denegado')], default='', max_length=32, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='members',
            field=models.ManyToManyField(blank=True, to='bd.Member', verbose_name='miembro'),
        ),
    ]
