# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 02:27
from __future__ import unicode_literals

import bd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_auto_20160422_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('femmale', 'Femenino'), ('male', 'Masculino')], max_length=32, validators=[bd.models.DNIValidator], verbose_name='Genero'),
        ),
    ]
