# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 03:53
from __future__ import unicode_literals

import bd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0008_auto_20160422_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=65, validators=[bd.models.OnlyLettersValidators], verbose_name='nombre'),
        ),
    ]
