# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 15:01
from __future__ import unicode_literals

import bd.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0010_auto_20160423_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxCount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='La cantidad maxima de personas en un cargo debe ser mayor que 1')], verbose_name='cantidad M\xe1xima')),
                ('name', models.CharField(max_length=64, validators=[bd.models.OnlyLettersValidators])),
            ],
        ),
        migrations.RemoveField(
            model_name='church_member',
            name='church',
        ),
        migrations.RemoveField(
            model_name='church_member',
            name='member',
        ),
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name': 'C\xe9lula'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name': 'Denominaci\xf3n', 'verbose_name_plural': 'Denominaciones'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instituci\xf3n', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='moneytransaction',
            options={'verbose_name': 'Transacci\xf3n Monetaria', 'verbose_name_plural': 'Transacciones Monetarias'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Canci\xf3n', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='directingChurch',
        ),
        migrations.AlterField(
            model_name='cell',
            name='address',
            field=models.CharField(max_length=124, verbose_name='direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='bd.Member', verbose_name='anfitri\xf3n'),
        ),
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.CharField(max_length=65, verbose_name='direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='church',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Designation', verbose_name='denominaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='church',
            name='phone',
            field=models.CharField(max_length=25, validators=[bd.models.PhoneValidator], verbose_name='tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.CharField(max_length=65, validators=[django.core.validators.EmailValidator('El correo no es v\xe1lido')], verbose_name='correo electr\xf3nico'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=25, validators=[bd.models.PhoneValidator], verbose_name='tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=65, verbose_name='direci\xf3n'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dni',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11, 'El n\xfamero debe tener 11 d\xedgitos'), django.core.validators.MaxLengthValidator(11, 'El n\xfamero debe tener 11 d\xedgitos'), bd.models.DNIValidator], verbose_name='n\xfamero de identidad'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('femmale', 'Femenino'), ('male', 'Masculino')], max_length=32, verbose_name='g\xe9nero'),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=65, verbose_name='ocupaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[bd.models.PhoneValidator], verbose_name='tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='description',
            field=models.CharField(max_length=124, verbose_name='descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Institution', verbose_name='instituci\xf3n que dona/recibe'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.Member', verbose_name='miembro que dona/recibe'),
        ),
        migrations.DeleteModel(
            name='Church_Member',
        ),
        migrations.AddField(
            model_name='charge',
            name='members',
            field=models.ManyToManyField(to='bd.Member', verbose_name='ocupan el cargo'),
        ),
    ]
