# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0011_auto_20160424_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': 'Cargo'},
        ),
    ]
