# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0012_auto_20160424_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='church',
        ),
        migrations.RemoveField(
            model_name='member',
            name='church',
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='church',
        ),
        migrations.DeleteModel(
            name='Church',
        ),
    ]
