# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0013_auto_20160424_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='score',
            field=models.FileField(null=True, upload_to='Partituras', verbose_name='partitura'),
        ),
    ]
